# Q7) Calculate Mean, Median, Mode, Variance, Standard Deviation, Range &     comment about the values / draw inferences, for the given dataset For Points,Score,Weigh> Find Mean, Median, Mode, Variance, Standard Deviation, and Range and also Comment about the values/ Draw some inferences.
Use Q7.csv file

In [1]:
import pandas as pd
from statistics import mean, median, mode, variance, stdev

In [2]:
# Load the dataset
df = pd.read_csv(r"C:\Users\Pritee\OneDrive\Documents\data science assignments\assignments\basic statistics level 1\Q7.csv")
df

             Unnamed: 0  Points  Score  Weigh
0             Mazda RX4    3.90  2.620  16.46
1         Mazda RX4 Wag    3.90  2.875  17.02
2            Datsun 710    3.85  2.320  18.61
3        Hornet 4 Drive    3.08  3.215  19.44
4     Hornet Sportabout    3.15  3.440  17.02
5               Valiant    2.76  3.460  20.22
6            Duster 360    3.21  3.570  15.84
7             Merc 240D    3.69  3.190  20.00
8              Merc 230    3.92  3.150  22.90
9              Merc 280    3.92  3.440  18.30
10            Merc 280C    3.92  3.440  18.90
11           Merc 450SE    3.07  4.070  17.40
12           Merc 450SL    3.07  3.730  17.60
13          Merc 450SLC    3.07  3.780  18.00
14   Cadillac Fleetwood    2.93  5.250  17.98
15  Lincoln Continental    3.00  5.424  17.82
16    Chrysler Imperial    3.23  5.345  17.42
17             Fiat 128    4.08  2.200  19.47
18          Honda Civic    4.93  1.615  18.52
19       Toyota Corolla    4.22  1.835  19.90
20        Toyota Corona    3.70  2.465  20.01
21     Dodge Challenger    2.76  3.520  16.87
22          AMC Javelin    3.15  3.435  17.30
23           Camaro Z28    3.73  3.840  15.41
24     Pontiac Firebird    3.08  3.845  17.05
25            Fiat X1-9    4.08  1.935  18.90
26        Porsche 914-2    4.43  2.140  16.70
27         Lotus Europa    3.77  1.513  16.90
28       Ford Pantera L    4.22  3.170  14.50
29         Ferrari Dino    3.62  2.770  15.50
30        Maserati Bora    3.54  3.570  14.60
31           Volvo 142E    4.11  2.780  18.60

In [5]:
# Extract columns
points = df['Points']
score = df['Score']
weight = df['Weigh']

In [6]:
# Function to calculate mode (as mode may have multiple values)
def calculate_mode(data):
    try:
        mode_val = mode(data)
        return [mode_val]
    except StatisticsError:
        return None

In [7]:
# Calculate Mean, Median, Mode, Variance, Standard Deviation, and Range

In [8]:
# for points column

In [9]:
mean_points = mean(points)
median_points = median(points)
mode_points = calculate_mode(points)
variance_points = variance(points)
std_dev_points = stdev(points)
range_points = max(points) - min(points)

In [10]:
# Print the results
print("For Points:")
print(f"Mean: {mean_points:.2f}")
print(f"Median: {median_points}")
print(f"Mode: {mode_points}")
print(f"Variance: {variance_points:.2f}")
print(f"Standard Deviation: {std_dev_points:.2f}")
print(f"Range: {range_points}\n")

For Points:
Mean: 3.60
Median: 3.6950000000000003
Mode: [3.92]
Variance: 0.29
Standard Deviation: 0.53
Range: 2.17

In [11]:
#for score column

In [12]:
mean_score = mean(score)
median_score = median(score)
mode_score = calculate_mode(score)
variance_score = variance(score)
std_dev_score = stdev(score)
range_score = max(score) - min(score)

In [13]:
print("For Score:")
print(f"Mean: {mean_score:.2f}")
print(f"Median: {median_score}")
print(f"Mode: {mode_score}")
print(f"Variance: {variance_score:.2f}")
print(f"Standard Deviation: {std_dev_score:.2f}")
print(f"Range: {range_score}\n")

For Score:
Mean: 3.22
Median: 3.325
Mode: [3.44]
Variance: 0.96
Standard Deviation: 0.98
Range: 3.9110000000000005

In [14]:
mean_weight = mean(weight)
median_weight = median(weight)
mode_weight = calculate_mode(weight)
variance_weight = variance(weight)
std_dev_weight = stdev(weight)
range_weight = max(weight) - min(weight)

In [15]:
print("For Weight:")
print(f"Mean: {mean_weight:.2f}")
print(f"Median: {median_weight}")
print(f"Mode: {mode_weight}")
print(f"Variance: {variance_weight:.2f}")
print(f"Standard Deviation: {std_dev_weight:.2f}")
print(f"Range: {range_weight}")

For Weight:
Mean: 17.85
Median: 17.71
Mode: [17.02]
Variance: 3.19
Standard Deviation: 1.79
Range: 8.399999999999999